// Données par défaut — synchronisées avec APPLI_CIRCO(2).xlsx
const DEFAULT_DATA = {
  "circo": [
    {
      "id": "circo-1",
      "nom": "Noura Bader",
      "fonction": "IEN",
      "email": "Noura.Bader@ac-amiens.fr",
      "telephone": "",
      "portable": "06 52 19 90 17",
      "avatar": ""
    },
    {
      "id": "circo-2",
      "nom": "Laure BARREYAT",
      "fonction": "Secrétaire",
      "email": "ien02.laon@ac-amiens.fr",
      "telephone": "03 23 26 22 11",
      "portable": "",
      "avatar": ""
    },
    {
      "id": "circo-3",
      "nom": "Dorothée Parisot",
      "fonction": "CPC",
      "email": "Dorothee.leduc@ac-amiens.fr",
      "telephone": "03 65 32 02 64",
      "portable": "06 08 37 41 32",
      "avatar": ""
    },
    {
      "id": "circo-4",
      "nom": "Léonie GOBEAUX",
      "fonction": "CPC",
      "email": "Leonie.Berlemont@ac-amiens.fr",
      "telephone": "03 23 26 20 66",
      "portable": "06 18 18 56 36",
      "avatar": ""
    },
    {
      "id": "circo-5",
      "nom": "Marie-Hélène MOULIERE-GALLOIS",
      "fonction": "CPC",
      "email": "marie-helene.mouliere@ac-amiens.fr",
      "telephone": "03 23 26 22 10",
      "portable": "06 47 49 24 47",
      "avatar": ""
    },
    {
      "id": "circo-6",
      "nom": "Fabien VAN DEN HENDE",
      "fonction": "ERUN",
      "email": "fvan-den-hende@ac-amiens.fr",
      "telephone": "03 23 26 22 17",
      "portable": "06 27 80 62 47",
      "avatar": ""
    }
  ],
  "ecoles": [
    {
      "id": "ecole-1",
      "nom": "ANIZY LE CHÂTEAU MAT",
      "directeur": "Marie Laure Marcellin",
      "telephone": "03 23 20 00 61",
      "portable": "06 30 09 45 31",
      "email": "ce.0021760C@ac-amiens.fr",
      "decharges": "mardi",
      "horaires": "8h30/11h40   13h25/16h25",
      "secteurCollege": "Anizy",
      "commune": "ANIZY LE CHÂTEAU - Belleuse"
    },
    {
      "id": "ecole-2",
      "nom": "ANIZY LE CHÂTEAU - Belleuse",
      "directeur": "Laurent GAY",
      "telephone": "03 23 80 99 22",
      "portable": "06 14 99 83 21",
      "email": "ce.0021949H@ac-amiens.fr",
      "decharges": "mardi et  1V/3",
      "horaires": "8h35/11h35   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "ANIZY LE CHÂTEAU - Belleuse"
    },
    {
      "id": "ecole-3",
      "nom": "BOURGUIGNON SOUS MONTBAV",
      "directeur": "Jean-Luc Labrevoir",
      "telephone": "03 23 24 19 57",
      "portable": "06 38 93 55 59",
      "email": "ce.0020144W@ac-amiens.fr",
      "decharges": "6 jours /an",
      "horaires": "09h00/12h00   14h00/17H00",
      "secteurCollege": "Anizy",
      "commune": "BOURGUIGNON SOUS MONTBAV"
    },
    {
      "id": "ecole-4",
      "nom": "BRANCOURT EN LAONNOIS",
      "directeur": "Manon Masse",
      "telephone": "09 61 68 15 61 \nmat : 03 23 20 33 95",
      "portable": "06 60 38 86 23",
      "email": "ce.0020151D@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "BRANCOURT EN LAONNOIS"
    },
    {
      "id": "ecole-5",
      "nom": "CESSIERES",
      "directeur": "Cyril Maily",
      "telephone": "03 23 24 16 04",
      "portable": "07 83 95 34 33",
      "email": "ce.0020198E@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "09h00/12h00   14h00/17H00",
      "secteurCollege": "Anizy",
      "commune": "CESSIERES"
    },
    {
      "id": "ecole-6",
      "nom": "CHAVIGNON",
      "directeur": "Vincent Gobinet",
      "telephone": "03 23 21 61 01",
      "portable": "07.77.93.36.29",
      "email": "ce.0020264B@ac-amiens.fr",
      "decharges": "Vendredi",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "CHAVIGNON"
    },
    {
      "id": "ecole-7",
      "nom": "FAUCOUCOURT",
      "directeur": "Elise Pierson",
      "telephone": "03 23 80 37 52",
      "portable": "06 28 06 89 12",
      "email": "ce.0020449C@ac-amiens.fr",
      "decharges": "6 jours /an",
      "horaires": "09h00/12h00   14h00/17H00",
      "secteurCollege": "Anizy",
      "commune": "FAUCOUCOURT"
    },
    {
      "id": "ecole-8",
      "nom": "MERLIEUX ET FOUQUEROLLES",
      "directeur": "tanneur Audrey",
      "telephone": "03 23 80 16 25",
      "portable": "06 31 54 75 96",
      "email": "ce.0020683G@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "MERLIEUX ET FOUQUEROLLES"
    },
    {
      "id": "ecole-9",
      "nom": "LOUIS ARAGON-PINON",
      "directeur": "Jacqueline Dewulf",
      "telephone": "03 23 80 17 97",
      "portable": "06 87 31 40 64",
      "email": "ce.0020903W@ac-amiens.fr",
      "decharges": "Jeudi",
      "horaires": "8h30/12h00   13h45/16h15",
      "secteurCollege": "Anizy",
      "commune": "PINON"
    },
    {
      "id": "ecole-10",
      "nom": "PINON Maternelle",
      "directeur": "Frédéric Garreau",
      "telephone": "03 23 80 22 25",
      "portable": "06 83 37 24 84",
      "email": "ce.0020905Y@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h40/11h50   13h40/16h25",
      "secteurCollege": "Anizy",
      "commune": "PINON"
    },
    {
      "id": "ecole-11",
      "nom": "PREMONTRE",
      "directeur": "Marie Charlotte Defresne",
      "telephone": "03 23 80 50 72",
      "portable": "06 83 62 29 33",
      "email": "ce.0020925V@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h25/11h25   13h25/16h25",
      "secteurCollege": "Anizy",
      "commune": "PREMONTRE"
    },
    {
      "id": "ecole-12",
      "nom": "ROYAUCOURT ET CHAILVET",
      "directeur": "Maïté ropital",
      "telephone": "09 67 31 61 29",
      "portable": "06 33 21 35 40",
      "email": "ce.0020784S@ac-amiens.fr",
      "decharges": "6 jours /an",
      "horaires": "09h05/12h05   14h05/17h05",
      "secteurCollege": "Anizy",
      "commune": "ROYAUCOURT ET CHAILVET"
    },
    {
      "id": "ecole-13",
      "nom": "SUZY",
      "directeur": "Amandine NOBLECOURT",
      "telephone": "09 60 08 95 49",
      "portable": "06 79 25 21 36",
      "email": "ce.0021212G@ac-amiens.fr",
      "decharges": "6 jours /an",
      "horaires": "09h05/12h05   14h05/17h05",
      "secteurCollege": "Anizy",
      "commune": "SUZY"
    },
    {
      "id": "ecole-14",
      "nom": "URCEL",
      "directeur": "Frédérique Achin",
      "telephone": "03 23 21 13 80",
      "portable": "06 25 61 13 75",
      "email": "ce.0021248W@ac-amiens.fr",
      "decharges": "Mardi",
      "horaires": "8h35/11h45   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "URCEL"
    },
    {
      "id": "ecole-15",
      "nom": "VAUXAILLON",
      "directeur": "Margaux Blechet",
      "telephone": "03 23 80 26 70",
      "portable": "06 37 56 27 63",
      "email": "ce.0021264N@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Anizy",
      "commune": "VAUXAILLON"
    },
    {
      "id": "ecole-16",
      "nom": "ATHIES SOUS LAON",
      "directeur": "Minette Cécile",
      "telephone": "03 23 24 56 44",
      "portable": "06 50 52 39 20",
      "email": "ce.0021550Z@ac-amiens.fr",
      "decharges": "mardi et 1 V/3",
      "horaires": "8h45/12h00   13h45/16h30",
      "secteurCollege": "Charl",
      "commune": "ATHIES SOUS LAON"
    },
    {
      "id": "ecole-17",
      "nom": "ATHIES SOUS LAON mat",
      "directeur": "Elisabeth Duchange",
      "telephone": "03 23 24 58 31",
      "portable": "06 11 23 08 27",
      "email": "ce.0021707V@ac-amiens.fr",
      "decharges": "mardi",
      "horaires": "8h45/12h00   13h45/16h30",
      "secteurCollege": "Charl",
      "commune": "ATHIES SOUS LAON"
    },
    {
      "id": "ecole-18",
      "nom": "BRUYERES ET MONTBERAULT",
      "directeur": "Chenu Sandrine",
      "telephone": "03 23 24 81 65",
      "portable": "06 60 73 44 98",
      "email": "ce.0021770N@ac-amiens.fr",
      "decharges": "jeudi et vendredi",
      "horaires": "8h45/11h45   13h30/16h30",
      "secteurCollege": "Charl",
      "commune": "BRUYERES ET MONTBERAULT"
    },
    {
      "id": "ecole-19",
      "nom": "EPPES",
      "directeur": "Anaïs Brebant",
      "telephone": "03 23 24 25 73",
      "portable": "06 08 87 50 08",
      "email": "ce.0020411L@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/11h45   13h45/16h30",
      "secteurCollege": "Charl",
      "commune": "EPPES"
    },
    {
      "id": "ecole-20",
      "nom": "ARDON-LAON",
      "directeur": "Florence Noizet",
      "telephone": "03 23 22 85 87",
      "portable": "06 14 01 51 17",
      "email": "ce.0022095S@ac-amiens.fr",
      "decharges": "mardi",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-21",
      "nom": "BOIS DE BREUIL-LAON",
      "directeur": "Emmanuel Maton",
      "telephone": "03 23 22 85 88",
      "portable": "06 64 04 64 80",
      "email": "ce.0020975Z@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h40/12h00   14h10/16h50",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-22",
      "nom": "CITE-LAON",
      "directeur": "Mylène Siméon",
      "telephone": "03 23 22 86 28",
      "portable": "06 08 97 26 17",
      "email": "ce.0020976A@ac-amiens.fr",
      "decharges": "lundi et 1V/3",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-23",
      "nom": "HELENE BOUCHER-LAON",
      "directeur": "Christine Vin",
      "telephone": "03 23 22 86 29",
      "portable": "06 75 21 83 85",
      "email": "ce.0021649G@ac-amiens.fr",
      "decharges": "Jeudi",
      "horaires": "8h35/11h55   13h25/16h25",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-24",
      "nom": "LA FONTAINE Maternelle",
      "directeur": "Jérome lespayendel",
      "telephone": "03 23 22 86 43",
      "portable": "06 89 07 58 99",
      "email": "ce.0021481Z@ac-amiens.fr",
      "decharges": "lundi",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-25",
      "nom": "JEAN DE LA FONTAINE Elem",
      "directeur": "Lucie Hurrier",
      "telephone": "03 23 22 85 98",
      "portable": "06 68 85 64 59",
      "email": "ce.0021531D@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-26",
      "nom": "MOULIN ROUX-LAON",
      "directeur": "Isabelle Alavoine",
      "telephone": "03 23 22 86 44",
      "portable": "06 28 70 24 07",
      "email": "ce.0021815M@ac-amiens.fr",
      "decharges": "Jeudi",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-27",
      "nom": "SAINT-EXUPERY N 1-LAON",
      "directeur": "Frédéric Labarre",
      "telephone": "03 23 22 86 07",
      "portable": "06 86 90 83 08",
      "email": "ce.0020996X@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-28",
      "nom": "SAINT EXUPERY Mat",
      "directeur": "Magaly Calvin",
      "telephone": "03 23 22 86 46",
      "portable": "06 72 04 12 62",
      "email": "ce.0020998Z@ac-amiens.fr",
      "decharges": "vendredi",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Charl",
      "commune": "LAON"
    },
    {
      "id": "ecole-29",
      "nom": "AULNOIS SOUS LAON",
      "directeur": "Sandrine Geoffray",
      "telephone": "03 23 22 81 72",
      "portable": "06 37 77 56 45",
      "email": "ce.0021827A@ac-amiens.fr",
      "decharges": "jeudi et 1V/3",
      "horaires": "8h45/11h45   13h30/16h30",
      "secteurCollege": "Lenain",
      "commune": "AULNOIS SOUS LAON"
    },
    {
      "id": "ecole-30",
      "nom": "CHAMBRY",
      "directeur": "Emmanuel Huart",
      "telephone": "03.23.79.20.39 -\nmat 03.23.79.42.16",
      "portable": "06 86 85 03 61",
      "email": "ce.0020201H@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h50/12h00   13h20/16h30",
      "secteurCollege": "Lenain",
      "commune": "CHAMBRY"
    },
    {
      "id": "ecole-31",
      "nom": "CHAMPFLEURY-LAON",
      "directeur": "Vanessa LEROY",
      "telephone": "03 23 22 85 89",
      "portable": "06 78 96 44 42",
      "email": "ce.0020988N@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Lenain",
      "commune": "LAON"
    },
    {
      "id": "ecole-32",
      "nom": "DELAUNAY-LAON",
      "directeur": "Virginie Douchin",
      "telephone": "03 23 22 85 99",
      "portable": "06 01 83 17 89",
      "email": "ce.0022028U@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Lenain",
      "commune": "LAON"
    },
    {
      "id": "ecole-33",
      "nom": "FESTIEUX",
      "directeur": "nan",
      "telephone": "03 23 24 21 59",
      "portable": "06 50 64 91 40",
      "email": "ce.0020512W@ac-amiens.fr",
      "decharges": "mardi",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Lenain",
      "commune": "FESTIEUX"
    },
    {
      "id": "ecole-34",
      "nom": "GILBERT LOBJOIS-LAON",
      "directeur": "Isabelle Dupont",
      "telephone": "03 23 22 86 09",
      "portable": "06 28 32 30 19",
      "email": "ce.0020993U@ac-amiens.fr",
      "decharges": "jeudi",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Lenain",
      "commune": "LAON"
    },
    {
      "id": "ecole-35",
      "nom": "ILE DE FRANCE-LAON",
      "directeur": "Sandra Coquelle",
      "telephone": "03 23 22 85 96",
      "portable": "06 43 34 93 03",
      "email": "ce.0021855F@ac-amiens.fr",
      "decharges": "Totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Lenain",
      "commune": "LAON"
    },
    {
      "id": "ecole-36",
      "nom": "ANATOLE FRANCE-LAON",
      "directeur": "Valérie Berthier",
      "telephone": "03 23 22 85 86",
      "portable": "06 83 10 59 57",
      "email": "ce.0020984J@ac-amiens.fr",
      "decharges": "lundi et V 1/3",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Mermoz",
      "commune": "LAON"
    },
    {
      "id": "ecole-37",
      "nom": "CHIVY LES ETOUVELLES",
      "directeur": "Isabelle Bocq",
      "telephone": "03 23 20 49 88",
      "portable": "06 79 56 12 99",
      "email": "ce.0020288C@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "9h00/12h00   13h30/16h30",
      "secteurCollege": "Mermoz",
      "commune": "CHIVY LES ETOUVELLES"
    },
    {
      "id": "ecole-38",
      "nom": "CREPY",
      "directeur": "Baptiste Chabbal",
      "telephone": "03 23 20 91 23",
      "portable": "06 58 90 11 70",
      "email": "ce.0021634R@ac-amiens.fr",
      "decharges": "lundi mardi",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Mermoz",
      "commune": "CREPY"
    },
    {
      "id": "ecole-39",
      "nom": "FOURDRAIN",
      "directeur": "Annie Pernes",
      "telephone": "03 23 25 70 09",
      "portable": "06 34 90 85 16",
      "email": "ce.0021041W@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "9h00/12h00   13h30/16h30",
      "secteurCollege": "Mermoz",
      "commune": "FOURDRAIN"
    },
    {
      "id": "ecole-40",
      "nom": "LOUISE MACAULT N 2-LAON",
      "directeur": "Cédric Desprez",
      "telephone": "03 23 22 85 97",
      "portable": "06 84 53 96 10",
      "email": "ce.0020981F@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Mermoz",
      "commune": "LAON"
    },
    {
      "id": "ecole-41",
      "nom": "LOUISE MACAULT- Mat",
      "directeur": "Sophie Feistel",
      "telephone": "03 23 22 86 42",
      "portable": "06 84 64 63 46",
      "email": "ce.0020982G@ac-amiens.fr",
      "decharges": "totale",
      "horaires": "8h30/12h00   14h00/16h30",
      "secteurCollege": "Mermoz",
      "commune": "LAON"
    },
    {
      "id": "ecole-42",
      "nom": "MONS EN LAONNOIS",
      "directeur": "Paméla WRIK",
      "telephone": "03 23 23 74 83",
      "portable": "06 87 15 58 15",
      "email": "ce.0020709K@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h55/11h55   13h55/16h55",
      "secteurCollege": "Mermoz",
      "commune": "MONS EN LAONNOIS"
    },
    {
      "id": "ecole-43",
      "nom": "MONS EN LAONNOIS LEFEVRE",
      "directeur": "Pascale Ollivier",
      "telephone": "03 23 23 38 14   mat: 03 23 24 16 21",
      "portable": "06 51 06 60 46",
      "email": "ce.0021730V@ac-amiens.fr",
      "decharges": "Lundi",
      "horaires": "9h00/12h00   14h00/17h00",
      "secteurCollege": "Mermoz",
      "commune": "MONS EN LAONNOIS"
    },
    {
      "id": "ecole-44",
      "nom": "PRESLES ET THIERNY",
      "directeur": "Florence Didier",
      "telephone": "03 23 20 18 85",
      "portable": "06 81 38 76 10",
      "email": "ce.0020928Y@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h35/11h55   13h50/16h40",
      "secteurCollege": "Mermoz",
      "commune": "PRESLES ET THIERNY"
    },
    {
      "id": "ecole-45",
      "nom": "VIVAISE",
      "directeur": "Justine De Boysson Genteur",
      "telephone": "03 23 20 90 10",
      "portable": "06 17 01 36 08",
      "email": "ce.0021347D@ac-amiens.fr",
      "decharges": "1/mois",
      "horaires": "8h30/11h30   13h30/16h30",
      "secteurCollege": "Mermoz",
      "commune": "VIVAISE"
    }
  ],
  "mairies": [
    {
      "id": "mairie-1",
      "commune": "ANIZY LE CHÂTEAU - Belleuse",
      "maire": "M. CENTONZE",
      "portable": "",
      "adresse": "1 place Rochechouart 02320 ANIZY LE GRAND",
      "telephone": "03 23 80 11 98",
      "email": "mairie@anizylegrand.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. MORLET",
      "telCC": "03 23 61 12 17",
      "emailCC": "accueil@picardiedeschateaux.fr"
    },
    {
      "id": "mairie-2",
      "commune": "AULNOIS SOUS LAON",
      "maire": "M. DUMAY",
      "portable": "",
      "adresse": "1 Rue du Tour de Place, 02000 Aulnois-sous-Laon",
      "telephone": "03 23 22 80 11",
      "email": "mairieaulnois@gmail.com",
      "syndicatScolaire": "",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "contact@ca-paysdelaon.fr"
    },
    {
      "id": "mairie-3",
      "commune": "BOURGUIGNON SOUS MONTBAV",
      "maire": "Mme VILLER",
      "portable": "",
      "adresse": "2 rue de l'école 02000 bourguignon sous Montbavin",
      "telephone": "03 23 24 15 20",
      "email": "mairie-bourguignon.montbavin@wanadoo.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "Matthieu Fraise",
      "emailSyndicat": "mairie@vaucelles-et-beffecourt.fr",
      "telSyndicat": "03 23 23 45 74",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-4",
      "commune": "BRANCOURT EN LAONNOIS",
      "maire": "Mme ROUYER",
      "portable": "",
      "adresse": "42 rue de la croix blanche 02320 Brancourt en Laonnois",
      "telephone": "03 23 80 21 59",
      "email": "mairie@brancourt-en-laonnois.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. MORLET",
      "telCC": "03 23 61 12 17",
      "emailCC": "accueil@picardiedeschateaux.fr"
    },
    {
      "id": "mairie-5",
      "commune": "CESSIERES",
      "maire": "M. BERTHELOT",
      "portable": "",
      "adresse": "1 ruelle Buet 02320 Cessières",
      "telephone": "03 23 24 14 49",
      "email": "mairie.cessieressuzy02@gmail.com",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-6",
      "commune": "CHAMBRY",
      "maire": "Mme LEFEBVRE",
      "portable": "",
      "adresse": "39 bis rue Jean Jaurès 02000 Chambry",
      "telephone": "03 23 23 03 55",
      "email": "mairie@02chambry.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    },
    {
      "id": "mairie-7",
      "commune": "CHAVIGNON",
      "maire": "Mme BOURNONVILLE",
      "portable": "06.81.53.39.69",
      "adresse": "1 Pl. d'Haï Phong, 02000 Chavignon",
      "telephone": "03.23.21.61.05",
      "email": "chavignon.mairie@wanadoo.fr",
      "syndicatScolaire": "RPI",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-8",
      "commune": "FAUCOUCOURT",
      "maire": "M. CENTONZE",
      "portable": "",
      "adresse": "1 place Rochechouart 02320 ANIZY LE GRAND",
      "telephone": "03 23 80 11 98",
      "email": "mairie@anizylegrand.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "M. BERTHELOT",
      "emailSyndicat": "mairie.cessieressuzy02@gmail.com",
      "telSyndicat": "03 23 24 14 49",
      "communauteCommunes": "OUI",
      "presidentCC": "M. MORLET",
      "telCC": "03 23 61 12 17",
      "emailCC": "accueil@picardiedeschateaux.fr"
    },
    {
      "id": "mairie-9",
      "commune": "FESTIEUX",
      "maire": "M. BUVRY",
      "portable": "06 24 03 98 44",
      "adresse": "8 rue de la Croix-aux-Arbres, 02840 Festieux",
      "telephone": "03 23 23 03 86",
      "email": "mairiedefestieux@gmail.com",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    },
    {
      "id": "mairie-10",
      "commune": "MERLIEUX ET FOUQUEROLLES",
      "maire": "M. CLERMONT",
      "portable": "",
      "adresse": "Mairie, rue des victimes de Comportet 02000 Merlieux",
      "telephone": "03.23.80.20.98",
      "email": "mairie.merlieux@sfr.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-11",
      "commune": "PINON",
      "maire": "M. GRAZINA BOULANDE",
      "portable": "",
      "adresse": "1 Place Charles de Gaulle 02320 PINON",
      "telephone": "03 23 80 11 08",
      "email": "mairie@villedepinon.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-12",
      "commune": "PREMONTRE",
      "maire": "M.DOMINGUEZ",
      "portable": "",
      "adresse": "6 rue Eugène-Potelet 02320 Prémontré",
      "telephone": "03 23 80 52 13",
      "email": "mairie.premontre@wanadoo.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. MORLET",
      "telCC": "03 23 61 12 17",
      "emailCC": "accueil@picardiedeschateaux.fr"
    },
    {
      "id": "mairie-13",
      "commune": "ROYAUCOURT ET CHAILVET",
      "maire": "M. LE RUDULIER",
      "portable": "",
      "adresse": "1 place Eliane Valaud 02000 Royaucourt-et-Chailvet",
      "telephone": "03.23.21.59.74",
      "email": "mairie.royaucourt-chailvet@wanadoo.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "Matthieu Fraise",
      "emailSyndicat": "mairie@vaucelles-et-beffecourt.fr",
      "telSyndicat": "03 23 23 45 74",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-14",
      "commune": "SUZY",
      "maire": "M. BERTHELOT",
      "portable": "",
      "adresse": "1 ruelle Buet 02320 Cessières",
      "telephone": "03 23 24 14 49",
      "email": "mairie.cessieressuzy02@gmail.com",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-15",
      "commune": "URCEL",
      "maire": "M. PIERSON",
      "portable": "07 71 11 26 08",
      "adresse": "16, rue de l'église     02000 URCEL",
      "telephone": "03 23 21 60 20",
      "email": "mairie-urcel@outlook.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. MORLET",
      "telCC": "03 23 61 12 17",
      "emailCC": "accueil@picardiedeschateaux.fr"
    },
    {
      "id": "mairie-16",
      "commune": "VAUXAILLON",
      "maire": "M. LEJEUNE",
      "portable": "",
      "adresse": "28, rue du 102ème RI 02320 Vauxaillon",
      "telephone": "03 23 80 12 83",
      "email": "mairie-de-vauxaillon@orange.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-17",
      "commune": "ATHIES SOUS LAON",
      "maire": "Mme DELPLANQUE",
      "portable": "",
      "adresse": "place du 11 novembre 02840 Athies-sous-Laon",
      "telephone": "03 23 24 52 38",
      "email": "mairie.athies02@wanado.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    },
    {
      "id": "mairie-18",
      "commune": "BRUYERES ET MONTBERAULT",
      "maire": "M. MONTCOURTOIS",
      "portable": "",
      "adresse": "Place du Général de Gaulle 02860 Bruyères-et-Montbérault",
      "telephone": "03 23 24 74 77",
      "email": "mairie.bruyeres@wanadoo.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "M.LIENARD",
      "emailSyndicat": "siscotlaonnois@gmail.com",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-19",
      "commune": "EPPES",
      "maire": "M. AMY",
      "portable": "",
      "adresse": "280 rue du Monument 02840 Eppes France",
      "telephone": "03 23 24 25 75",
      "email": "mairie.eppes@orange.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-20",
      "commune": "LAON",
      "maire": "M. DELHAYE",
      "portable": "",
      "adresse": "place du Général Leclerc 02000 Laon",
      "telephone": "03 23 22 30 30",
      "email": "cmartin@ville-laon.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-21",
      "commune": "CHIVY LES ETOUVELLES",
      "maire": "M. RABOUILLE",
      "portable": "",
      "adresse": "6 Rue du Bon-Puits, 02000 Chivy-lès-Étouvelles",
      "telephone": "03 23 20 62 47",
      "email": "mairie.chivylesetouvelles@wanadoo.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-22",
      "commune": "CREPY",
      "maire": "Mme MEZZAROBBA",
      "portable": "",
      "adresse": "43 Rue Malézieux Briquet, 02870 Crépy",
      "telephone": "03 23 20 90 33",
      "email": "mairie.crepy@crepy-aisne.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "Mme MEZZAROBBA",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    },
    {
      "id": "mairie-23",
      "commune": "FOURDRAIN",
      "maire": "M. DESEUSTE",
      "portable": "",
      "adresse": "8 Rue Léon Gruel, 02870 Fourdrain",
      "telephone": "03 23 20 93 65",
      "email": "mairie.fourdrain@wanadoo.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. IGNASZAK",
      "telCC": "03 23 39 94 94",
      "emailCC": "direction@ctlf.fr"
    },
    {
      "id": "mairie-24",
      "commune": "MONS EN LAONNOIS",
      "maire": "M. CHARLES",
      "portable": "",
      "adresse": "1 Gd Pl. Grande Pce d'Aix en Provence, 02000 Mons-en-Laonnois",
      "telephone": "03 23 24 12 93",
      "email": "mons.mairie@wanadoo.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "Matthieu Fraise",
      "emailSyndicat": "mairie@vaucelles-et-beffecourt.fr",
      "telSyndicat": "03 23 23 45 74",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    },
    {
      "id": "mairie-25",
      "commune": "PRESLES ET THIERNY",
      "maire": "M. KYRIACOS",
      "portable": "",
      "adresse": "2, rue de l'église 02860 Presles-et-Thierny",
      "telephone": "03 23 20 69 13",
      "email": "commune@presles-thierny.fr",
      "syndicatScolaire": "OUI",
      "presidentSyndicat": "M.LIENARD",
      "emailSyndicat": "siscotlaonnois@gmail.com",
      "telSyndicat": "",
      "communauteCommunes": "NON",
      "presidentCC": "",
      "telCC": "",
      "emailCC": ""
    },
    {
      "id": "mairie-26",
      "commune": "VIVAISE",
      "maire": "M. VIANAS",
      "portable": "",
      "adresse": "1 Av. d'Emptinne, 02870 Vivaise",
      "telephone": "03 23 20 89 38",
      "email": "vivaise.mairie@orange.fr",
      "syndicatScolaire": "NON",
      "presidentSyndicat": "",
      "emailSyndicat": "",
      "telSyndicat": "",
      "communauteCommunes": "OUI",
      "presidentCC": "M. DELHAYE",
      "telCC": "03 23 22 31 00",
      "emailCC": "https://www.ca-paysdelaon.fr/contact/"
    }
  ]
};
